"""Claude Code adapter — generates CLAUDE.md from memory notes."""

from __future__ import annotations

import logging
from pathlib import Path

from aimem.core.config import AdapterConfig
from aimem.core.note import Note
from aimem.core.repository import MemoryRepository

logger = logging.getLogger(__name__)

DEFAULT_CONFIG = AdapterConfig(
    output="~/.claude/CLAUDE.md",
    include=[
        "identity/*",
        "knowledge/languages/*",
        "knowledge/tools/*",
        "procedures/workflows/*",
        "procedures/patterns/*",
    ],
    format="markdown",
    max_tokens=4000,
)


def export_claude(
    repo: MemoryRepository,
    output: Path | None = None,
    config: AdapterConfig | None = None,
) -> Path:
    """Generate CLAUDE.md from memory notes.

    Args:
        repo: The memory repository to export from.
        output: Output file path (default from config).
        config: Adapter configuration (default: built-in).

    Returns:
        Path to the generated CLAUDE.md file.
    """
    cfg = config or repo.config.adapters.get("claude", DEFAULT_CONFIG)
    target = output or Path(cfg.output).expanduser()

    notes = repo.list_notes()
    # Filter notes by include patterns
    included = _filter_notes(notes, cfg.include, repo.root)

    sections: list[str] = []
    sections.append("# AI Memory — Auto-generated Configuration")
    sections.append("")
    sections.append(
        "<!-- Generated by aimem. Do not edit manually — "
        "changes will be overwritten. -->"
    )
    sections.append("")

    for note in included:
        sections.append(f"## {note.title}")
        sections.append("")
        sections.append(note.body)
        sections.append("")

    content = "\n".join(sections)

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")

    logger.info("Exported Claude config to %s (%d notes)", target, len(included))
    return target


def _filter_notes(notes: list[Note], patterns: list[str], root: Path) -> list[Note]:
    """Filter notes by glob-style include patterns."""
    from fnmatch import fnmatch

    included: list[Note] = []
    for note in notes:
        rel = str(note.path.relative_to(root))
        for pattern in patterns:
            if fnmatch(rel, pattern):
                included.append(note)
                break
    return included
